
default: &default
  adapter: postgresql
  encoding: unicode
  username: test
  password: test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: img_dev

test:
  <<: *default
  database: img_test

production:
  <<: *default
  database: img_prod
